Bug 1383123 - Generate HTTPS URLs instead of HTTP in buildbot
mozilla/build-blobber pull request #3
Opened 2017-07-25 07:45 UTC by SJasoria

URL provided to Treeherder by buildbot should be HTTPS, otherwise mixed content error is thrown by the browser.

2017-07-25 12:53 UTC, wlach commented on blobber/amazons3_backend.py
> +    amazon_baseurl = key.generate_url(expires_in=0)
I think this should just be `return key.generate_url(expires_in=0)` (removing the code below)

2017-07-27 15:51 UTC, wlach commented on blobber/amazons3_backend.py
> +    return key.generate_url(expires_in=0)
You should also remove urlparse from the top of the file as it's no longer needed. This is causing travis to fail:
https://travis-ci.org/mozilla/build-blobber/builds/257412292?utm_source=github_status&utm_medium=notification

2017-07-28 18:23 UTC, MihaiTabara approved these changes
With the apologies for the delays in answering as well as the mention that this is code from my 2013 internship and ... stuff I haven't touched since then :) 
But the change looks good! Clearly a good and more than welcomed cleanup&refactoring! Thanks! 👍

2017-08-22 13:56 UTC, rail requested changes

2017-08-22 13:56 UTC, rail commented on blobber/amazons3_backend.py
> +    return key.generate_url(expires_in=0)
The last line should be `return key.generate_url(expires_in=0, query_auth=False)`, otherwise boto returns a signed URL, which is expired.

2017-08-22 13:57 UTC, MihaiTabara commented
Thanks @rail for catching that. Can you make a comment in the bug 1383123 as well?

2017-08-22 13:57 UTC, rail commented
Sorry for the delay with this. The service hasn't been touched in years (it works, right! :) ). We can deploy the change after my comment is addressed.

2017-08-22 14:14 UTC, edmorley commented
> The last line should be return key.generate_url(expires_in=0, query_auth=False), otherwise boto returns a signed URL, which is expired.

Yeah I agree, think my comment here was missed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1383123#c14

2017-08-22 15:41 UTC, rail approved these changes
Thank you!

2017-08-22 15:42 UTC, merged